[workspace]
resolver = "2"
members = [
    "bevy-hello",
    "bevy-cube",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.10.0", features = ["dynamic_linking"] }