[package]
name = "bevy-cube"
description = "Drawing a 3d cube in a window"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bevy.workspace = true